version: "3.8"
services:
    frontend:
        image: node:20-alpine # Используем базовый образ node для dev
        container_name: project_frontend_dev
        command: sh -c "npm install && npm run dev -- --host" # Установить и запустить
        working_dir: /app
        volumes:
            - ./Frontend:/app
            - frontend_node_modules:/app/node_modules
        ports:
            - "80:80" # Порт Vite
        networks:
            - app-network
        depends_on:
            - backend
        profiles:
            - dev
volumes:
    frontend_node_modules:
