version: "3.8"

services:
    postgres:
        image: postgres:17.4-alpine
        container_name: project_postgres
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - app-network

    redis:
        image: redis:7.4.2-alpine
        container_name: project_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
        networks:
            - app-network

    backend:
        build:
            context: ./Backend
            dockerfile: Dockerfile
        container_name: project_backend
        env_file:
            - .env
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80

            - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}

            - Redis__ConnectionString=redis

            - Minio__Endpoint=minio:9000
            - Minio__AccessKey=${MINIO_USER}
            - Minio__SecretKey=${MINIO_PASSWORD}
            - Minio__UseSSL=false
            - Minio__BucketName=${MINIO_DEFAULT_BUCKET}
        networks:
            - app-network
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            minio:
                condition: service_healthy

    frontend:
        build:
            context: ./Frontend
            dockerfile: Dockerfile
        container_name: project_frontend
        ports:
            - "80:80"
        environment:
            - REACT_APP_API_URL=/api
        networks:
            - app-network
        depends_on:
            - backend

    minio:
        image: minio/minio:latest
        container_name: project_minio
        command: server /data --console-address ":9001"
        env_file:
            - .env
        environment:
            MINIO_ROOT_USER: ${MINIO_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
            MINIO_DEFAULT_BUCKET: ${MINIO_DEFAULT_BUCKET}
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_data:/data
            - ./setup-minio.sh:/setup-minio.sh
            - ./entrypoint.sh:/entrypoint.sh
        entrypoint: /entrypoint.sh
        networks:
            - app-network
        healthcheck:
            test:
                ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
    redis_data:
    minio_data:
